dist: xenial
language: cpp
compiler: gcc
# Boost
addons:
  apt:
    update: true
    sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - boost1.67
      - lcov
install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
  - cd ..
after_success:
  - chmod +x ./testCoverage.sh
  - ./testCoverage.sh -t 1 -s 1
