dist: xenial
language: cpp
compiler: gcc
# Boost
addons:
  apt:
    update: true
    sources:
        - sourceline: 'ppa:mhier/libboost-latest'
        - ubuntu-toolchain-r-test
    packages:
      - g++-8
      - boost1.67
install:
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-8 90
script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test